0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,17 +1,26 @@
-#!/usr/bin/env bash
-# This script transfers a file from user to server
+#!/bin/bash
 
-# Check if exactly 4 parameters were passed
-if [ $# -ne 4 ]; then
-	    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	        exit 1
+# Script to transfer a file to a remote server
+
+# Check if the number of arguments is less than 4
+if [ "$#" -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
-# Execute SCP with specified options
-scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+# Assign variables to each argument for clarity
+PATH_TO_FILE="$1"
+IP="$2"
+USERNAME="$3"
+PATH_TO_SSH_KEY="$4"
+
+# Use scp with strict host key checking disabled to transfer the file
+scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
+
+# Check if scp succeeded
 if [ $? -eq 0 ]; then
-	    echo "File transfer successful."
-    else
-	        echo "Error during file transfer."
-		    exit 1
+    echo "File transferred successfully."
+else
+    echo "Error transferring file."
+    exit 1
 fi
