debugging

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,28 +1,17 @@
 #!/usr/bin/env bash
-# This script transfers a file to a specified server using SCP
+# This script transfers a file from user to server
 
+# Check if exactly 4 parameters were passed
 if [ $# -ne 4 ]; then
-	  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	    exit 1
+	    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	        exit 1
 fi
 
-PATH_TO_FILE="$1"
-IP="$2"
-USERNAME="$3"
-PATH_TO_SSH_KEY="$4"
-
-# Ensure that the SSH private key file exists
-if [ ! -f "$PATH_TO_SSH_KEY" ]; then
-	  echo "Error: SSH key file '$PATH_TO_SSH_KEY' does not exist."
-	    exit 1
+# Execute SCP with specified options
+scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+if [ $? -eq 0 ]; then
+	    echo "File transfer successful."
+    else
+	        echo "Error during file transfer."
+		    exit 1
 fi
-
-# Ensure that the file to be transferred exists
-if [ ! -f "$PATH_TO_FILE" ]; then
-	  echo "Error: File '$PATH_TO_FILE' to transfer does not exist."
-	    exit 1
-fi
-
-# Execute SCP command
-scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~
-
